### PR TITLE
added ShareSheet().view_file() method

### PR DESCRIPTION
**Pull request by vesellov**

### CODE REVIEW

**Comment by RobertFlatt** [comment]
Great. 
Could you please add a *little* to the README about what the call does. 
When someone might want to use it, what to expect when it is used.

I will merge and release, may be a few days till I build for pypi (will be version 0.1.0).

**Comment by vesellov** [comment]
Sure @RobertFlatt !
I updated the README file a little bit and added another sentence about that new method.
:+1:

**Comment by Android-for-Python** [comment]
Thanks

**Comment by Android-for-Python** [comment]
@vesellov 
FYI Now released on pypi as 0.1.0

**Comment by vesellov** [comment]
Thank you much for cooperation!

**Pull request merged**
